<!DOCTYPE html>
<html lang="ru">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">
  <meta http-equiv="cache-control" content="max-age=0" />
  <meta http-equiv="cache-control" content="no-cache" />
  <meta http-equiv="pragma" content="no-cache" />
 <?php if(isset($data['title'])){?>
  <title><?= $data['title'] ?></title>
<?php } ?>
  <link href="<?=$controller->site_dir ?>include/css/bootstrap.min.css" rel="stylesheet">
  <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">
  <link href="<?=$controller->site_dir ?>include/css/styles.css" rel="stylesheet">
  
</head>
<body>
  <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
      <div class="navbar-header">
      	<div class="section-heading">Тестовое задание</div>
      </div>

      
    </div>
  </nav>
  <section>
    <div class="container">
    	<div class="row">
			<div class="col-md-12">
				<div class="row">
					<!-- <div class="col-md-3">
						<ul class="nav left-menu">
							<li>
								<a href="#" class="left-menu-sec-title"></a>
							</li>
						</ul>
					</div> -->
					
					<div class="col-md-12">
					    <!--div class="container"-->
					    <div class="row"><br></div>
					    <div class="row">