<div class="row">
   <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
      <div class="panel panel-default">
          <div class="panel-heading">
            <span class="panel-title">Введите ID раздела каталога сайта book24.ru для получения списка товаров</span>
          </div>
          <div class="panel-body">
          
<form action="<?=$data["form_action"] ?>" method="post" id="import_form_book" />
	<input type="hidden" name="do" value="import">
	<div class="row answer_box">
    	<?php 
    	if(isset($data["answer"]) && !empty($data["answer"]['errors'])){
    		foreach ($data["answer"]['errors'] as $error){?>
    		<div class="answer_error"><?=$error?></div>
    	<?php }
    	}?>
	</div>

	<div class="row">
    	<div class="form-group col-sm-3 col-xs-12">
      		<label for="import_form_book_sec">ID каталога</label>
      		<input type="text" name="form_data[section_id]" id="import_form_book_sec"
      			placeholder="Например, 1361"
      			value="<?=(isset($data['form_data']['section_id']) ? $data['form_data']['section_id'] : '') ?>" 
      			class="form-control">
      	</div>
      	<div class="form-group col-sm-3 col-xs-12">
      		<label></label>
      		<input class="btn btn-primary form-control" type="submit" value="Получить данные">
      	</div>
	</div>

</form>
			</div>
		</div>
	</div>
</div>
